# Generated by Django 4.2.1 on 2023-06-24 02:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_number', models.CharField(max_length=50, null=True, unique=True)),
                ('stu_pic', models.FileField(null=True, upload_to='')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('add_date', models.DateField(default=datetime.datetime.now, null=True)),
                ('ph1', models.CharField(max_length=10, null=True, unique=True)),
                ('ph2', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=64, null=True, unique=True)),
                ('email2', models.EmailField(blank=True, max_length=64, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default=None, max_length=10, null=True)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('AB+', 'AB+'), ('B+', 'B+'), ('O+', 'O+'), ('A-', 'A-'), ('B-', 'B-'), ('AB-', 'AB+'), ('O+', 'O-')], default=None, max_length=10)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('zip', models.CharField(max_length=8, null=True)),
                ('address1', models.CharField(max_length=255, null=True)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('student_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_name', models.CharField(max_length=100, null=True)),
                ('father_email1', models.EmailField(blank=True, max_length=64, null=True)),
                ('father_email2', models.EmailField(blank=True, max_length=64, null=True)),
                ('mother_email1', models.EmailField(blank=True, max_length=64, null=True)),
                ('mother_email2', models.EmailField(blank=True, max_length=64, null=True)),
                ('father_occupation', models.CharField(blank=True, max_length=50, null=True)),
                ('father_ph1', models.CharField(blank=True, max_length=10, null=True)),
                ('father_ph2', models.CharField(blank=True, max_length=10, null=True)),
                ('mother_occupation', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_ph1', models.CharField(blank=True, max_length=10, null=True)),
                ('mother_ph2', models.CharField(blank=True, max_length=10, null=True)),
                ('aadhar_no', models.CharField(max_length=12, null=True, unique=True)),
                ('highest_qualification', models.CharField(blank=True, choices=[('Master Degree', 'Master Degree'), ('Bachelor`s Degree', 'Bachelor`s Degree'), ('Diploma', 'Diploma'), ('Senior Secondary', 'Senior Secondary'), ('Secondary', 'Secondary'), ('Primary', 'Primary')], max_length=50, null=True)),
                ('degree', models.CharField(blank=True, choices=[('MBA', 'MBA'), ('MCA', 'MCA'), ('M.COM', 'M.COM'), ('M.SC', 'M.SC'), ('MA', 'MA'), ('M.TECH', 'MTECH'), ('MBBS', 'MBBS'), ('M.E', 'ME'), ('BBA', 'BBA'), ('B.COM', 'B.COM'), ('B.SC', 'BSC'), ('MA', 'BA'), ('B.TECH', 'BTECH'), ('B.E', 'BE')], max_length=50, null=True)),
                ('pre_school', models.CharField(blank=True, max_length=100, null=True)),
                ('hdyk_rsu', models.CharField(choices=[('Google_Bussiness', 'Google_Bussiness'), ('Newspaper', 'Newspaper'), ('Social_Media', 'Social_Media'), ('Friends OR Relative', 'Friends OR Relative')], max_length=50, null=True)),
                ('category', models.CharField(blank=True, choices=[('sc', 'SC'), ('st', 'ST'), ('obc', 'OBC'), ('gen', 'Gen')], max_length=100, null=True)),
                ('created_at', models.DateField(default=datetime.datetime.now, null=True)),
                ('updated_at', models.DateField(default=datetime.datetime.now, null=True)),
            ],
        ),
    ]
